version: '3'

services:
  galaxy:
    image: galaxy-dev:latest
    volumes:
      - ${PWD}:/galaxy:z
    environment:
      - TMUX
      - TEST
      - DJANGO_SETTINGS_MODULE=galaxy.settings.development
      - GALAXY_DB_URL=postgres://galaxy:galaxy@postgres:5432/galaxy
    ports:
      - '8000:8000'
    links:
      - postgres
      - rabbitmq

  postgres:
    image: centos/postgresql-95-centos7
    ports:
      - '2345:5432'
    environment:
      - POSTGRESQL_DATABASE=galaxy
      - POSTGRESQL_USER=galaxy
      - POSTGRESQL_PASSWORD=galaxy
      - POSTGRESQL_ADMIN_PASSWORD=postgres

  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=galaxy
      - RABBITMQ_DEFAULT_PASS=galaxy
      - RABBITMQ_DEFAULT_VHOST=galaxy

  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_DB=galaxy
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_WRITE_USER=galaxy
      - INFLUXDB_WRITE_USER_PASSWORD=galaxy

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    links:
      - influxdb
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    ports:
      - '9090:9090'
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
    links:
      - galaxy:galaxy.svc
