- name: Install epel
  yum: name=epel-release

- name: Install nodejs
  yum: name="{{ item }}"
  with_items:
  - nodejs
  - npm

- name: Download dumb-init
  get_url:
    url: https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64
    dest: /usr/local/bin/dumb-init
    owner: root
    group: root
    mode: 755

name: Create galaxy directory
  file: 
    path: /galaxy
    state: directory
    owner: root
    group: root
    mode: 775 

- name: Copy package.json
  copy:
    src: "{{ lookup('pipe','dirname `pwd`') }}/package.json"
    dest: /galaxy/package.json
    owner: root
    group: root
    mode: 775

- name: Install node packages
  npm: path=/galaxy state=latest

- name: Install gulp globally
  npm: name=gulp global=yes

- name: Install less globally
  npm: name=less global=yes
