version: '3'

services:
  web:
    image: galaxy:latest
    command: ['/bin/bash', '-c', '/entrypoint.sh manage waitenv && /entrypoint.sh manage migrate --noinput && /entrypoint.sh run web']
    environment:
      - GALAXY_SECRET_KEY=secret
      - GALAXY_DB_URL="postgres://galaxy:galaxy@postgres:5432/galaxy"
      - GALAXY_RABBITMQ_HOST=rabbitmq
      - GALAXY_RABBITMQ_PASSWORD=galaxy
    ports:
      - '8000:8000'
    links:
      - postgres
      - rabbitmq

  worker:
    image: galaxy:latest
    command: ['/bin/bash', '-c', '/entrypoint.sh manage waitenv --wait-for web:8000 && /entrypoint.sh run worker']
    environment:
      - GALAXY_SECRET_KEY=secret
      - GALAXY_DB_URL=postgres://galaxy:galaxy@postgres:5432/galaxy
      - GALAXY_RABBITMQ_HOST=rabbitmq
      - GALAXY_RABBITMQ_PASSWORD=galaxy
      - C_FORCE_ROOT=1
    links:
      - postgres
      - rabbitmq


  postgres:
    image: postgres:9.5.4
    environment:
      - POSTGRES_DB=galaxy
      - POSTGRES_USER=galaxy
      - POSTGRES_PASSWORD=galaxy

  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=galaxy
      - RABBITMQ_DEFAULT_PASS=galaxy
      - RABBITMQ_DEFAULT_VHOST=galaxy
