# s3 settings
galaxy_bucket: galaxy.ansibleworks.com
galaxy_encryption_password: ""

# Postgresql DB settings
galaxy_postgresql_dbname: "galaxy"
galaxy_postgresql_username: "galaxy"
galaxy_postgresql_password: "galaxy"
galaxy_postgresql_hostname: "*"
galaxy_postgresql_port: "*"
