- name: Install epel
  yum: name=epel-release

- name: Install nodejs
  yum: name="{{ item }}"
  with_items:
  - nodejs
  - npm

- name: Download dumb-init
  get_url:
    url: https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64
    dest: /usr/local/bin/dumb-init
    owner: root
    group: root
    mode: 755

- name: Install node packages
  npm: path=/galaxy state=latest

- name: Install gulp globally
  npm: name=gulp global=yes

- name: Install less globally
  npm: name=less global=yes

- name: Copy entrypoint.sh 
  copy:
    src: "{{ role_path }}/files/entrypoint.sh"
    dest: /usr/bin/entrypoint.sh 
    mode: 0775

