---
galaxy_info:
  author: 'Brian Akins, Dustin Brown & Datadog'
  description: Install Datadog agent and configure checks
  license: Apache2
  min_ansible_version: 1.6
  platforms:
    - name: Ubuntu
      versions:
        - lucid
        - maverick
        - natty
        - oneiric
        - precise
        - quantal
        - raring
        - saucy
        - trusty
        - utopic
        - vivid
        - xenial
    - name: Debian
      versions:
        - squeeze
        - wheezy
        - jessie
    - name: EL
      versions:
        - 7
        - 6
        - 5
  categories:
    - monitoring
dependencies: []
