version: '3'

services:
  web:
    image: galaxy:latest
    command: ['/bin/bash', '-c', '/entrypoint.sh manage waitenv && /entrypoint.sh manage migrate --noinput && /entrypoint.sh manage rebuild_index --noinput && /entrypoint.sh manage rebuild_galaxy_indexes && /entrypoint.sh run web']
    environment:
      - GALAXY_SECRET_KEY=secret
      - DATABASE_URL="postgres://galaxy:galaxy@postgres:5432/galaxy"
      - GALAXY_RABBITMQ_HOST=rabbitmq
      - GALAXY_RABBITMQ_PASSWORD=galaxy
      - GALAXY_MEMCACHE_HOST=memcache
      - GALAXY_ELASTICSEARCH_HOST=elastic
    ports:
      - '8000:8000'
    links:
      - postgres
      - elastic
      - memcache
      - rabbitmq

  worker:
    image: galaxy:latest
    command: ['/bin/bash', '-c', '/entrypoint.sh manage waitenv --wait-for web:8000 && /entrypoint.sh run worker']
    environment:
      - GALAXY_SECRET_KEY=secret
      - DATABASE_URL="postgres://galaxy:galaxy@postgres:5432/galaxy"
      - GALAXY_RABBITMQ_HOST=rabbitmq
      - GALAXY_RABBITMQ_PASSWORD=galaxy
      - GALAXY_MEMCACHE_HOST=memcache
      - GALAXY_ELASTICSEARCH_HOST=elastic
      - C_FORCE_ROOT=1
    links:
      - postgres
      - elastic
      - rabbitmq

  postgres:
    image: postgres:9.5.4
    environment:
      - POSTGRES_DB=galaxy
      - POSTGRES_USER=galaxy
      - POSTGRES_PASSWORD=galaxy

  elastic:
    user: elasticsearch
    expose:
    - 9200
    - 9300
    image: 'ansible/galaxy-elasticsearch:2.4.6'

  memcache:
    image: memcached:latest

  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=galaxy
      - RABBITMQ_DEFAULT_PASS=galaxy
      - RABBITMQ_DEFAULT_VHOST=galaxy
