version: "2"
services:
  django:
    image: centos:7
    working_dir: /galaxy
    environment:
      - PGPASSWORD={{ galaxy_postgres_password }}
    volumes:
      - ${PWD}:/galaxy:z
      - {{ galaxy_log_dir }}:/galaxy_logs:Z
      - {{ galaxy_config_path }}:/etc/galaxy:Z
    links:
      - postgres
      - elastic
      - memcache
      - rabbit
    user: django
    dev_overrides:
      command: [/usr/local/bin/dumb-init, /galaxy/ansible/start_development.sh]
      ports:
        - "8000:8000"

  postgres:
    image: postgres:9.5.4
    environment:
      - POSTGRES_PASSWORD={{ galaxy_postgres_password }}
      - POSTGRES_USER={{ galaxy_postgres_user }}
      - POSTGRES_DB={{ galaxy_postgres_db }} 

  elastic:
    image: elasticsearch:2.4.1

  memcache:
    image: memcached:latest

  rabbit:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER={{ galaxy_rabbitmq_user }}
      - RABBITMQ_DEFAULT_PASS={{ galaxy_rabbitmq_pass }}
      - RABBITMQ_DEFAULT_VHOST={{ galaxy_rabbitmq_vhost }}

  gulp:
    image: centos:7
    volumes:
      - ${PWD}:/galaxy:z
    command: ["/bin/true"]
    dev_overrides:
      working_dir: /galaxy
      command: [/usr/local/bin/dumb-init, /usr/bin/gulp]

registries: {}
