
---
# develop.yml 

galaxy_env: "DEV"
galaxy_project_dir: "/galaxy"
galaxy_log_dir: "/galaxy_logs"
galaxy_configure_supervisor: False
galaxy_create_superuser: True

# general Django settings

galaxy_site_env: "DEV"
galaxy_site_name: "localhost"
galaxy_site_aliases: ['localhost', '127.0.0.1', '0.0.0.0']
galaxy_send_email: False

# Outbound SMTP settings

galaxy_email_hostname: ""
galaxy_email_port: 25
galaxy_email_username: ""
galaxy_email_password: ""

# logging handlers
galaxy_accounts_handler: console
galaxy_main_handler: console
galaxy_allauth_handler: console
galaxy_django_handler: django_logfile

# galaxy_acounts_handler: galaxy_logfile
# galaxy_main_handler: galaxy_logfile
# galaxy_allauth_handler: allauth_logfile
# galaxy_django_handler: django_logfile

