---
galaxy_info:
  author: Chris Houseknecht
  description: Using pg_basebackup clone a PostgreSQL cluster from a remote host.
  company: Ansible, Inc.
  license: MIT 
  min_ansible_version: 1.2
  platforms:
  - name: EL
    versions:
    - all
    - 5
    - 6
    - 7
  categories:
  - database
  - database:sql

dependencies: []
  
