# general Django settings

galaxy_site_env: "DEV"
galaxy_project_dir: "/galaxy_devel"
galaxy_dist_dir: "/galaxy_devel/dist"
galaxy_log_dir: "/galaxy_devel/logs"
galaxy_site_name: "galaxy.local"
galaxy_site_aliases: []
galaxy_make_sdist: True
galaxy_send_email: False
galaxy_configure_supervisor: False
galaxy_official_build: no
galaxy_install_dev_tools: True
galaxy_install_postgresql: True

# Outbound SMTP settings

galaxy_email_hostname: ""
galaxy_email_port: 25
galaxy_email_username: ""
galaxy_email_password: ""

# Apache configuration settings

galaxy_ssl_cert: "/etc/pki/tls/certs/localhost.crt"
galaxy_ssl_key: "/etc/pki/tls/private/localhost.key"
#galaxy_ssl_cachain: "/etc/pki/tls/certs/ca-bundle.crt"
galaxy_ssl_cachain: null

# Github API settings

galaxy_github_api_token: ""
